[profile.default]
src = 'src'
out = 'out'
libs = ['lib']
optimizer = true
optimizer_runs = 1  # Optimize for deployment size
solc = "0.8.24"
via_ir = true  # Disable via_ir as it seems to increase size

# Trim metadata/footer bytes
bytecode_hash = "none"        # drops IPFS/BZZ hash
cbor_metadata = false         # (Foundry >= v1.2) remove CBOR trailer

# Optional: target recent EVM for better IR opts
#evm_version = "paris"
